-- ============================================================
-- HEIM ERP — 기업 71개 import (HEIM ADS OS Firestore 미러)
-- ============================================================
-- 0016(HVP 22명) 이후 실행. 기존 회사 전체 교체.
-- 소개 HVP는 이름으로 매칭. 단계는 투자 파이프라인 → 영업 단계 매핑.

DELETE FROM companies;

INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('robin', '김수정', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='전승재' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('마이닝오천', '박성훈', 'AI 에이전트 개발', 'proposal', NULL, 'heim_ads_import', '담당 컨설턴트: 강영환 / IR: 완료 / 확인서: 발급 완료', NULL);
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('컨벤져스', '권중우', '마케팅 AI 에이전트', 'contract', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='김경민' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('루카스에듀테이먼트', '장진민', '에듀테크', 'proposal', NULL, 'heim_ads_import', '담당 컨설턴트: 강영환 / IR: 완료 / 확인서: 발급 완료', NULL);
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('디에이블', '소지영', '축산 난임 솔루션', 'proposal', NULL, 'heim_ads_import', '담당 컨설턴트: 기동현 / IR: 미제출 / 확인서: 미발급', (SELECT id FROM hvp WHERE name='김경민' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('온스페이스', '박종필', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='홍승희' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('미스터팍', '이지섭', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='김경민' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('큐엔에이에듀', '남궁영', '에듀테크', 'meeting_1st', NULL, 'heim_ads_import', '담당 컨설턴트: 박대성', (SELECT id FROM hvp WHERE name='김지선' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('빌리버스', '조현수', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='김경민' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('이팜헬스케어(케어랩)', '이복기', '처방전 플랫폼', 'proposal', NULL, 'heim_ads_import', '담당 컨설턴트: 강영환 / IR: 완료 / 확인서: 발급 완료', NULL);
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('포월드코리아', '김성년', NULL, 'received', '탈락', 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='지영주' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('처음청약', '장용', '청약 솔루션', 'contract', NULL, 'heim_ads_import', '담당 컨설턴트: 기동현', (SELECT id FROM hvp WHERE name='이규화' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('티움하나로', '임정효', '친환경자원회수기', 'received', NULL, 'heim_ads_import', '담당 컨설턴트: 박대성 / IR: 미제출', (SELECT id FROM hvp WHERE name='강승민' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('메디벤처스', '김경록', '의료기기 D2C', 'contract', NULL, 'heim_ads_import', '담당 컨설턴트: 기동현 / IR: 완료 / 확인서: 발급 완료', NULL);
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('현대글로버', '김준석', NULL, 'received', '탈락', 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='지영주' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('핀라이브', '이동영', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='홍성훈' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('이안애코스메틱', '김기태', NULL, 'received', '탈락', 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='지영주' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('다보자', '서재호', '네이버카페 기반 마케팅 솔루션', 'proposal', NULL, 'heim_ads_import', '담당 컨설턴트: 기동현 / IR: 검토 중 / 확인서: 미발급', NULL);
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('다원몬테소리', '박예솔', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='최수원' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('그랑페르', '이선행', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='이조원' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('레인보우팜', '류정희', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='고금상' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('헬스플러스', '최성원', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='김경민' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('케이피엠씨', '백영환', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='김경민' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('에녹스', '정일천', '마케팅 플랫폼', 'contract', NULL, 'heim_ads_import', '담당 컨설턴트: 기동현 / IR: 미제출 / 확인서: 미발급', NULL);
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('에이젠다', '안효인', '의료 차트 솔루션', 'contract', NULL, 'heim_ads_import', '담당 컨설턴트: 기동현 / IR: 검토 중 / 확인서: 미발급', (SELECT id FROM hvp WHERE name='안정환' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('이볼브', '신동수', 'AI', 'kickoff', NULL, 'heim_ads_import', '담당 컨설턴트: 강영환 / TIPS: WhryRZDN2subMuvLT4fi / IR: 완료 / 확인서: 발급 완료', NULL);
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('덴티버스', '박성진', '치과 기공 솔루션', 'contract', NULL, 'heim_ads_import', 'IR: 검토 중 / 확인서: 미발급', NULL);
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('스팩', '박운용', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='현기암' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('플레듀', '김진우', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='정재훈' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('펴다', '김형석', '우산공유플랫폼', 'contract', NULL, 'heim_ads_import', '담당 컨설턴트: 강영환 / IR: 제출 / 확인서: 발급 완료', (SELECT id FROM hvp WHERE name='안정환' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('어묵버거어묵피자', '김구현', NULL, 'received', '탈락', 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='지영주' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('킹스케어', '이수환', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='홍승희' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('네오플로우', NULL, NULL, 'proposal', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='최수원' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('파인드잇', '최강만', NULL, 'meeting_1st', NULL, 'heim_ads_import', '담당 컨설턴트: 박대성', NULL);
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('라훔나노테크', '이명훈', NULL, 'meeting_1st', NULL, 'heim_ads_import', '담당 컨설턴트: 박대성', (SELECT id FROM hvp WHERE name='지영주' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('네스젠', '한세훈', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='강태혁' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('에이 에이치 라이프', '박경식', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='지영주' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('나이테듀', '오영석', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='김경민' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('비와이즈솔루션', '정도성', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='김경민' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('무인화연구소', '박영욱', '무인카페', 'kickoff', NULL, 'heim_ads_import', '담당 컨설턴트: 강영환 / IR: 완료 / 확인서: 발급 완료', NULL);
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('삼현지피알', '김관태', '강관 응용 물저장 시스템', 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='지영주' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('뷰랩스', '양태란', '성형중개플랫폼', 'proposal', NULL, 'heim_ads_import', '담당 컨설턴트: 강영환 / TIPS: WhryRZDN2subMuvLT4fi / IR: 완료 / 확인서: 발급 완료', NULL);
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('차산후', '차대균', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='정재훈' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('파밀리데이터', '임일균', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='홍승희' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('코피다스', '이진희', '통합  OS 플랫폼', 'proposal', NULL, 'heim_ads_import', '담당 컨설턴트: 강영환 / TIPS: WhryRZDN2subMuvLT4fi / IR: 완료 / 확인서: 발급 완료', (SELECT id FROM hvp WHERE name='남지윤' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('나눔알파플러스', '모상구', '편의점 HR 솔루션', 'contract', NULL, 'heim_ads_import', '담당 컨설턴트: 기동현 / IR: 검토 중 / 확인서: 발급 완료', NULL);
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('노랑바나나', '김태리, 최이준', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='정재훈' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('미정', '최선우', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='정재훈' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('지우데이타', '이지영, 차진우', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='김경민' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('아유오케이바이오', '이영하', NULL, 'received', '탈락', 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='지영주' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('써니후드', '송진호', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='홍승희' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('닥터키트', '이세현', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='김경민' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('코코미디어', '노경호', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='이조원' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('프롭핀테크', '이유호', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='조대일' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('비엠제이', '김보미', '마케팅', 'kickoff', NULL, 'heim_ads_import', '담당 컨설턴트: 강영환 / TIPS: WhryRZDN2subMuvLT4fi / IR: 완료 / 확인서: 발급 완료', NULL);
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('모디온테크', '정한두', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='홍승희' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('워터크린시스템', '김진천', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='지영주' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('엔드게임벤처스', '홍유리', '뷰티', 'kickoff', NULL, 'heim_ads_import', '담당 컨설턴트: 강영환 / TIPS: WhryRZDN2subMuvLT4fi / IR: 완료 / 확인서: 발급 완료', NULL);
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('아이닥', '이찬영', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='홍성훈' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('에프디에스씨', '이규광', '바닥재 거래 플랫폼', 'contract', NULL, 'heim_ads_import', '담당 컨설턴트: 강영환 / IR: 검토 중 / 확인서: 미발급', NULL);
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('미라클 그룹', '남지윤', '정책자금 솔루션', 'contract', NULL, 'heim_ads_import', '담당 컨설턴트: 강영환 / TIPS: WhryRZDN2subMuvLT4fi / IR: 완료 / 확인서: 발급 완료', NULL);
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('벨라골드', '이희남', '금 플랫폼', 'proposal', NULL, 'heim_ads_import', '담당 컨설턴트: 기동현 / TIPS: WhryRZDN2subMuvLT4fi / IR: 완료 / 확인서: 발급 완료', NULL);
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('빵명장', '임정효', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='지영주' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('텀브샤인', '이쌍윤', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='홍승희' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('투비이스', '강해운', '무인카페', 'proposal', NULL, 'heim_ads_import', '담당 컨설턴트: 강영환 / TIPS: WhryRZDN2subMuvLT4fi / IR: 완료 / 확인서: 발급 완료', (SELECT id FROM hvp WHERE name='김경민' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('브랜드지놈', '박소희', '뷰티', 'kickoff', NULL, 'heim_ads_import', '담당 컨설턴트: 강영환 / IR: 완료 / 확인서: 발급 완료', NULL);
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('실비노', NULL, NULL, 'contract', NULL, 'heim_ads_import', '담당 컨설턴트: 강영환', (SELECT id FROM hvp WHERE name='이선용' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('더파', '최대희', '대안신용평가', 'contract', NULL, 'heim_ads_import', '담당 컨설턴트: 강영환 / IR: 검토 중 / 확인서: 미발급', NULL);
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('교연교구', '이봉님', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='정재훈' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('Vom AI', '정태준', NULL, 'received', NULL, 'heim_ads_import', NULL, (SELECT id FROM hvp WHERE name='김경민' LIMIT 1));
INSERT INTO companies (name, ceo_name, main_item, sales_stage, drop_reason, source, notes, hvp_id) VALUES ('예담라이프', '신성철', '장례 AI 에이전트', 'contract', NULL, 'heim_ads_import', '담당 컨설턴트: 강영환 / IR: 검토 중 / 확인서: 미발급', NULL);
